version: "2.1"
services:
  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: calibre
    volumes:
      - ${DATA_PATH}:/config
    ports:
      - 9080:8080
      - 9081:8081
    user: 0:0 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - PASSWORD= #
      - CLI_ARGS= #optional    
    restart: unless-stopped
